# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 10:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dublicate',
            name='mobile',
            field=models.CharField(default='+38(067)2162478', max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message="Phone number must be entered in the format: '+380(67)9999999'. Up to 15 digits allowed.", regex='^\\+380\\([0-9]{2}\\)[0-9]{7}$')]),
            preserve_default=False,
        ),
    ]
