# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_dublicate_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dublicate',
            name='mobile',
        ),
    ]
