# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170720_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
