# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_dublicate_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='home_phone',
            new_name='company',
        ),
        migrations.AddField(
            model_name='contact',
            name='business_phone',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='secondname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
