# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message="Phone number must be entered in the format: '+380(67)9999999'. Up to 15 digits allowed.", regex='^\\+380\\([0-9]{2}\\)[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
