# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_dublicate_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='home_phone',
            new_name='personal_phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='business_phone',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
