# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170801_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='media_url_list',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
