# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20171214_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
