# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20170803_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactphoto',
            options={'ordering': ['-load_date']},
        ),
        migrations.AddField(
            model_name='contactphoto',
            name='load_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x000002CEE7AF7198>/photos'),
        ),
        migrations.AlterField(
            model_name='contactphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x000002CEE7AF7198>/thumbs'),
        ),
    ]
