# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20171218_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
