# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20171220_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
    ]
