# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20170803_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='media_url_list',
        ),
        migrations.AddField(
            model_name='contactphoto',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x0000015FBA3761D0>/photos'),
        ),
        migrations.AlterField(
            model_name='contactphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x0000015FBA3761D0>/thumbs'),
        ),
    ]
