# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 06:26
from __future__ import unicode_literals

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20170807_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=contacts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='contactphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=contacts.models.user_directory_path),
        ),
    ]
