# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 14:36
from __future__ import unicode_literals

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20170808_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=contacts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
