runtime: python
env: flex
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT contact.wsgi

beta_settings:
    cloud_sql_instances: my-contacts-205212:europe-west3:contact-app

handlers:
- url: /static
  static_dir: static

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: mycontacts_app
#    MYSQL_DSN: mysql:unix_socket=/cloudsql/my-contacts-205212:europe-west3:contacts;dbname=contacts
#    MYSQL_USER: mycontact
#    MYSQL_PASSWORD: P@ssw0rd123
#[END env]

runtime_config:
  python_version: 3