runtime: python
env: flex
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT contact.wsgi

beta_settings:
    cloud_sql_instances: my-contacts-205212:europe-west3:contacts

handlers:
- url: /static
  static_dir: static

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: mycontacts_app
#[END env]

runtime_config:
  python_version: 3